name: pr
on:
  pull_request:
    branches:
    - main
jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build-plugins
        shell: pwsh
        run: |
          dotnet build src\solutions\pacmaptest\plugins\pacmaptest.plugins -c release



