name: pr
on:
  pull_request:
    branches:
      - main
env:
  solution_name: pacmaptest
  solution_src_root: src/solutions/pacmaptest

jobs:
  pr:
    runs-on: windows-latest 

    steps:
      - uses: actions/checkout@v2

      - name: build
        shell: pwsh
        run: |
          $currentDirectory = Get-Location
          cd $env:solution_src_root/pcf-components/DynamicTextInput
          npm install
          cd $currentDirectory
          dotnet build $env:solution_src_root -c release
      
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ${{ env.solution_src_root }}/bin/Release      