name: pr
on:
  pull_request:
    branches:
      - main
# env:
#   solution-name: pacmaptest
  
jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build-plugins
        shell: pwsh
        run: |
          dotnet build src\solutions\pacmaptest\plugins\pacmaptest.plugins -c release

      - name: pack-solution
        uses: microsoft/powerplatform-actions/pack-solution@latest
        with:
          solution-folder: src/solutions/pacmaptest/unpack-src
          solution-file: ${{ runner.temp }}/pacmaptest/pacmaptest.zip
          solution-type: Both
      
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ${{ runner.temp }}/${{ env.solution_name }}