name: pr
on:
  pull_request:
    branches:
      - main
env:
  solution_src_root: src/solutions/pacmaptest
  
jobs:
  pr:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: build-plugin
        run: |
          dotnet build $solution_src_root/plugins/pacmaptest.plugins -c release
      
      # Until GitHub Actions for Power Platform doesn't require us to use pac direcly
      # for certain commands, we need to use it directly.  So we set the path to pac
      # that ships with the Actions
      - name: set-pac-path
        uses: ./.github/actions/set-pac-path
      
      - name: pack-solution
        env:
          solution_folder: ${{ env.solution_src_root }}/unpack-src
          solution_file: ${{ runner.temp }}/pacmaptest/pacmaptest.zip
          map_file: ${{ env.solution_src_root }}/map.xml
        run: |
          pac solution pack -f $solution_folder -z $solution_file -m $map_file -p both

      # - name: pack-solution
      #   uses: microsoft/powerplatform-actions/pack-solution@0.4.3
      #   with:
      #     solution-folder: s${{ env.solution_src_root }}/unpack-src
      #     solution-file: ${{ runner.temp }}/pacmaptest/pacmaptest.zip
      #     solution-type: Both
      
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: artifact
      #     path: ${{ runner.temp }}/pacmaptest
      #